version: "3.9"
services:
  app:
    build: .
    container_name: nest1
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    environment:
      DB_HOST: mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql:/var/lib/mysql
    env_file:
      - .env

volumes:
  mysql:
    driver: local
